### ISSUE TITLE
Stats Test

### ISSUE THREAD

**Issue by vivekaxl** [vivekaxl/Rank_v2#4]

**Comment by vivekaxl** [comment]
WIP

**Comment by vivekaxl** [comment]
[sk_RankDifference.pdf](https://github.com/vivekaxl/Rank_v2/files/884696/sk_RankDifference.pdf)
[sk_Evaluations.pdf](https://github.com/vivekaxl/Rank_v2/files/884697/sk_Evaluations.pdf)

**Comment by timm** [comment]
is p-rank the fse paper?

so many examples where you use 100s of fewer evals?

cool!

**Comment by vivekaxl** [comment]
Yes. p-Rank is the FSE paper
